// Embeds ../fixtures/v1/*.json verbatim (raw JSON text, so number spellings such as 1e3 and
// 1.0 survive) into test/fixtures.g.dart, letting the same tests run in a browser where
// dart:io is unavailable. Run from packages/contracts/dart: `dart run tool/embed_fixtures.dart`.
// test/fixtures_files_test.dart (VM) fails when the embedded copy is stale.
import 'dart:io';

String render() {
  final files = Directory('../fixtures/v1')
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.json'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/embed_fixtures.dart from packages/contracts/fixtures/v1.')
    ..writeln('// Do not edit by hand.')
    ..writeln('const Map<String, String> embeddedFixtures = {');
  for (final f in files) {
    final text = f.readAsStringSync();
    if (text.contains("'''")) throw StateError('${f.path} contains a triple quote');
    out.writeln("  '${f.uri.pathSegments.last}': r'''$text''',");
  }
  out.writeln('};');
  return out.toString();
}

void main() => File('test/fixtures.g.dart').writeAsStringSync(render());

String readFile(String path) => File(path).readAsStringSync();
