// GENERATED by tool/embed_fixtures.dart from packages/contracts/fixtures/v1.
// Do not edit by hand.
const Map<String, String> embeddedFixtures = {
  'account_ref.json': r'''{
  "kind": "account_ref",
  "contract_version": 1,
  "valid": [
    {"name": "lowercase uuid", "value": {"auth_user_id": "00000000-0000-4000-8000-000000000002"}}
  ],
  "invalid": [
    {"name": "missing auth_user_id", "value": {}, "field_errors": {"auth_user_id": "required"}},
    {"name": "braced uuid", "value": {"auth_user_id": "{00000000-0000-4000-8000-000000000002}"}, "field_errors": {"auth_user_id": "invalid"}},
    {"name": "uuid without hyphens", "value": {"auth_user_id": "00000000000040008000000000000002"}, "field_errors": {"auth_user_id": "invalid"}},
    {"name": "member_id is not an account", "value": {"member_id": "00000000-0000-4000-8000-000000000001"}, "field_errors": {"auth_user_id": "required", "member_id": "unknown_field"}},
    {"name": "array", "value": ["00000000-0000-4000-8000-000000000002"], "field_errors": {"$": "must_be_object"}}
  ]
}
''',
  'actor.json': r'''{
  "kind": "actor",
  "contract_version": 1,
  "valid": [
    {"name": "member acting through an account", "value": {"kind": "member", "member_id": "00000000-0000-4000-8000-000000000001", "auth_user_id": "00000000-0000-4000-8000-000000000002"}},
    {"name": "system principal, no initiating member", "value": {"kind": "system", "system_principal_id": "00000000-0000-4000-8000-000000000003", "job_id": "00000000-0000-4000-8000-000000000001"}},
    {"name": "system principal, explicit null initiating member", "value": {"kind": "system", "system_principal_id": "00000000-0000-4000-8000-000000000003", "job_id": "00000000-0000-4000-8000-000000000001", "initiating_member_id": null}},
    {"name": "system principal with an initiating member recorded separately", "value": {"kind": "system", "system_principal_id": "00000000-0000-4000-8000-000000000003", "job_id": "00000000-0000-4000-8000-000000000001", "initiating_member_id": "00000000-0000-4000-8000-000000000002"}}
  ],
  "invalid": [
    {"name": "missing kind", "value": {"member_id": "00000000-0000-4000-8000-000000000001", "auth_user_id": "00000000-0000-4000-8000-000000000002"}, "field_errors": {"kind": "required"}},
    {"name": "unknown kind", "value": {"kind": "admin", "member_id": "00000000-0000-4000-8000-000000000001"}, "field_errors": {"kind": "invalid"}},
    {"name": "kind not a string", "value": {"kind": 1}, "field_errors": {"kind": "invalid"}},
    {"name": "member without account", "value": {"kind": "member", "member_id": "00000000-0000-4000-8000-000000000001"}, "field_errors": {"auth_user_id": "required"}},
    {"name": "member with null member_id", "value": {"kind": "member", "member_id": null, "auth_user_id": "00000000-0000-4000-8000-000000000002"}, "field_errors": {"member_id": "required"}},
    {"name": "member cannot carry system fields", "value": {"kind": "member", "member_id": "00000000-0000-4000-8000-000000000001", "auth_user_id": "00000000-0000-4000-8000-000000000002", "system_principal_id": "00000000-0000-4000-8000-000000000003"}, "field_errors": {"system_principal_id": "unknown_field"}},
    {"name": "system without job", "value": {"kind": "system", "system_principal_id": "00000000-0000-4000-8000-000000000003"}, "field_errors": {"job_id": "required"}},
    {"name": "system cannot select an arbitrary member actor", "value": {"kind": "system", "system_principal_id": "00000000-0000-4000-8000-000000000003", "job_id": "00000000-0000-4000-8000-000000000001", "member_id": "00000000-0000-4000-8000-000000000002"}, "field_errors": {"member_id": "unknown_field"}},
    {"name": "system with malformed initiating member", "value": {"kind": "system", "system_principal_id": "00000000-0000-4000-8000-000000000003", "job_id": "00000000-0000-4000-8000-000000000001", "initiating_member_id": "x"}, "field_errors": {"initiating_member_id": "invalid"}},
    {"name": "not an object", "value": "member", "field_errors": {"$": "must_be_object"}},
    {"name": "prototype-named key constructor", "value": {"kind": "member", "member_id": "00000000-0000-4000-8000-000000000001", "auth_user_id": "00000000-0000-4000-8000-000000000002", "constructor": "x"}, "field_errors": {"constructor": "unknown_field"}},
    {"name": "prototype-named key __proto__", "value": {"kind": "member", "member_id": "00000000-0000-4000-8000-000000000001", "auth_user_id": "00000000-0000-4000-8000-000000000002", "__proto__": "x"}, "field_errors": {"__proto__": "unknown_field"}},
    {"name": "prototype-named key toString", "value": {"kind": "member", "member_id": "00000000-0000-4000-8000-000000000001", "auth_user_id": "00000000-0000-4000-8000-000000000002", "toString": "x"}, "field_errors": {"toString": "unknown_field"}}
  ]
}
''',
  'command_request.json': r'''{
  "kind": "command_request",
  "contract_version": 1,
  "valid": [
    {"name": "create (expected_revision null)", "value": {"version": 1, "command": "fixture_counter.create", "request_id": "00000000-0000-4000-8000-000000000001", "expected_revision": null, "payload": {"intent_key": "synthetic"}}},
    {"name": "create with expected_revision omitted", "value": {"version": 1, "command": "fixture_counter.create", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}}},
    {"name": "mutation of an existing aggregate", "value": {"version": 1, "command": "fixture_counter.increment", "request_id": "00000000-0000-4000-8000-000000000002", "expected_revision": 4, "payload": {"counter_id": "00000000-0000-4000-8000-000000000003", "by": 1}}},
    {"name": "version written as 1.0", "value": {"version": 1.0, "command": "fixture_counter.create", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}}},
    {"name": "expected_revision written with an exponent", "value": {"version": 1, "command": "fixture_counter.increment", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}, "expected_revision": 1e3}},
    {"name": "longest command (127 chars)", "value": {"version": 1, "command": "fixture_counter.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}}}
  ],
  "invalid": [
    {"name": "not an object", "value": [], "field_errors": {"envelope": "must_be_object"}},
    {"name": "everything missing", "value": {}, "field_errors": {"version": "required", "command": "required", "request_id": "required", "payload": "must_be_object"}},
    {"name": "unsupported version", "value": {"version": 2, "command": "fixture_counter.create", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}}, "field_errors": {"version": "unsupported"}},
    {"name": "version as string", "value": {"version": "1", "command": "fixture_counter.create", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}}, "field_errors": {"version": "unsupported"}},
    {"name": "command without owner namespace", "value": {"version": 1, "command": "create", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}}, "field_errors": {"command": "invalid"}},
    {"name": "command not a string", "value": {"version": 1, "command": 7, "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}}, "field_errors": {"command": "invalid"}},
    {"name": "malformed request_id", "value": {"version": 1, "command": "fixture_counter.create", "request_id": "abc", "payload": {}}, "field_errors": {"request_id": "invalid"}},
    {"name": "expected_revision as string", "value": {"version": 1, "command": "fixture_counter.increment", "request_id": "00000000-0000-4000-8000-000000000001", "expected_revision": "4", "payload": {}}, "field_errors": {"expected_revision": "invalid"}},
    {"name": "expected_revision zero", "value": {"version": 1, "command": "fixture_counter.increment", "request_id": "00000000-0000-4000-8000-000000000001", "expected_revision": 0, "payload": {}}, "field_errors": {"expected_revision": "invalid"}},
    {"name": "payload array", "value": {"version": 1, "command": "fixture_counter.create", "request_id": "00000000-0000-4000-8000-000000000001", "payload": []}, "field_errors": {"payload": "must_be_object"}},
    {"name": "client-supplied actor is refused", "value": {"version": 1, "command": "fixture_counter.create", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}, "actor_id": "00000000-0000-4000-8000-000000000002"}, "field_errors": {"actor_id": "unknown_field"}},
    {"name": "uppercase request_id", "value": {"version": 1, "command": "fixture_counter.create", "request_id": "00000000-0000-4000-8000-00000000000A", "payload": {}}, "field_errors": {"request_id": "invalid"}},
    {"name": "version 1.5", "value": {"version": 1.5, "command": "fixture_counter.create", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}}, "field_errors": {"version": "unsupported"}},
    {"name": "command too long (128 chars)", "value": {"version": 1, "command": "fixture_counter.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}}, "field_errors": {"command": "invalid"}},
    {"name": "uppercase command", "value": {"version": 1, "command": "Fixture_counter.create", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}}, "field_errors": {"command": "invalid"}},
    {"name": "null command", "value": {"version": 1, "command": null, "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}}, "field_errors": {"command": "required"}},
    {"name": "prototype-named key constructor", "value": {"version": 1, "command": "fixture_counter.create", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}, "constructor": "x"}, "field_errors": {"constructor": "unknown_field"}},
    {"name": "prototype-named key __proto__", "value": {"version": 1, "command": "fixture_counter.create", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}, "__proto__": "x"}, "field_errors": {"__proto__": "unknown_field"}},
    {"name": "prototype-named key toString", "value": {"version": 1, "command": "fixture_counter.create", "request_id": "00000000-0000-4000-8000-000000000001", "payload": {}, "toString": "x"}, "field_errors": {"toString": "unknown_field"}}
  ]
}
''',
  'command_response.json': r'''{
  "kind": "command_response",
  "contract_version": 1,
  "valid": [
    {"name": "success", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "data": {"counter_id": "00000000-0000-4000-8000-000000000003", "value": 1}, "revision": 1}},
    {"name": "success with null data", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "data": null, "revision": 2}},
    {"name": "validation error with field errors", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "validation_failed", "message": "The request is not valid.", "field_errors": {"by": "invalid"}}},
    {"name": "error before request_id was readable", "value": {"request_id": null, "code": "validation_failed", "message": "The request is not valid.", "field_errors": {"request_id": "invalid"}}},
    {"name": "conflict with readable current revision", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "conflict", "message": "The item changed or this request was already used. Reload and try again.", "field_errors": {}, "current_revision": 5}},
    {"name": "unauthenticated", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "unauthenticated", "message": "Sign in to continue.", "field_errors": {}}},
    {"name": "forbidden", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "forbidden", "message": "You are not allowed to do this.", "field_errors": {}}},
    {"name": "not_found", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "not_found", "message": "The item was not found.", "field_errors": {}}},
    {"name": "rate_limited", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "rate_limited", "message": "Too many requests. Try again later.", "field_errors": {}}},
    {"name": "unavailable", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "unavailable", "message": "The service could not complete the request. Try again.", "field_errors": {}}},
    {"name": "server-only field error codes", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "validation_failed", "message": "The request is not valid.", "field_errors": {"zone": "unknown", "source_type": "unregistered", "amount": "scale_exceeded", "by": "out_of_range", "expected_revision": "must_be_null", "command": "unsupported"}}},
    {"name": "closed policy gate (public field, no internal gate name)", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "unavailable", "message": "The service could not complete the request. Try again.", "field_errors": {"policy": "gate_closed"}}},
    {"name": "identity refusal with a command-specific field error code (open vocabulary)", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "forbidden", "message": "You are not allowed to do this.", "field_errors": {"member_id": "last_admin"}}},
    {"name": "identity and cells command-specific codes", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "conflict", "message": "The item changed or this request was already used. Reload and try again.", "field_errors": {"session": "reauthenticate", "hold_id": "password_reset_required", "member_id": "held", "proposal_id": "stale", "change_id": "other_changes", "email": "already_approved", "cell_id": "current", "request_id": "decided", "recovery_email": "unverified"}, "current_revision": 7}},
    {"name": "field error code at the 63-character token limit", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "validation_failed", "message": "m", "field_errors": {"by": "abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}}},
    {"name": "success revision written with an exponent", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "data": {}, "revision": 1e3}}
  ],
  "invalid": [
    {"name": "unknown error code", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "sql_error", "message": "x", "field_errors": {}}, "field_errors": {"code": "invalid"}},
    {"name": "error without field_errors", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "forbidden", "message": "You are not allowed to do this."}, "field_errors": {"field_errors": "required"}},
    {"name": "error without request_id key", "value": {"code": "forbidden", "message": "m", "field_errors": {}}, "field_errors": {"request_id": "required"}},
    {"name": "error with null message", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "forbidden", "message": null, "field_errors": {}}, "field_errors": {"message": "required"}},
    {"name": "error message not a string", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "forbidden", "message": 3, "field_errors": {}}, "field_errors": {"message": "invalid"}},
    {"name": "field error value not a string", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "validation_failed", "message": "m", "field_errors": {"by": 1}}, "field_errors": {"field_errors": "invalid"}},
    {"name": "error leaking SQL detail key", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "unavailable", "message": "m", "field_errors": {}, "detail": "duplicate key value violates unique constraint"}, "field_errors": {"detail": "unknown_field"}},
    {"name": "error with fractional current revision", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "conflict", "message": "m", "field_errors": {}, "current_revision": 1.5}, "field_errors": {"current_revision": "invalid"}},
    {"name": "success without revision", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "data": {}}, "field_errors": {"revision": "required"}},
    {"name": "success without data key", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "revision": 1}, "field_errors": {"data": "required"}},
    {"name": "success with null request_id", "value": {"request_id": null, "data": {}, "revision": 1}, "field_errors": {"request_id": "required"}},
    {"name": "not an object", "value": "ok", "field_errors": {"$": "must_be_object"}},
    {"name": "field error code not lower_snake_case", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "validation_failed", "message": "m", "field_errors": {"by": "Too Big"}}, "field_errors": {"field_errors": "invalid"}},
    {"name": "field error code with a hyphen", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "validation_failed", "message": "m", "field_errors": {"by": "too-big"}}, "field_errors": {"field_errors": "invalid"}},
    {"name": "field error code starting with a digit", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "validation_failed", "message": "m", "field_errors": {"by": "9lives"}}, "field_errors": {"field_errors": "invalid"}},
    {"name": "empty field error code", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "validation_failed", "message": "m", "field_errors": {"by": ""}}, "field_errors": {"field_errors": "invalid"}},
    {"name": "field error code over 63 characters", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "code": "validation_failed", "message": "m", "field_errors": {"by": "abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}}, "field_errors": {"field_errors": "invalid"}},
    {"name": "success with error fields mixed in", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "data": {}, "revision": 1, "message": "m"}, "field_errors": {"message": "unknown_field"}},
    {"name": "prototype-named key constructor", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "data": {}, "revision": 1, "constructor": "x"}, "field_errors": {"constructor": "unknown_field"}},
    {"name": "prototype-named key __proto__", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "data": {}, "revision": 1, "__proto__": "x"}, "field_errors": {"__proto__": "unknown_field"}},
    {"name": "prototype-named key toString", "value": {"request_id": "00000000-0000-4000-8000-000000000001", "data": {}, "revision": 1, "toString": "x"}, "field_errors": {"toString": "unknown_field"}}
  ]
}
''',
  'instant.json': r'''{
  "kind": "instant",
  "contract_version": 1,
  "valid": [
    {"name": "server canonical form (microseconds)", "value": "2026-10-03T12:34:56.123456Z"},
    {"name": "whole seconds", "value": "2026-10-03T12:34:56Z"},
    {"name": "milliseconds", "value": "2026-10-03T12:34:56.789Z"},
    {"name": "leap day", "value": "2028-02-29T00:00:00Z"},
    {"name": "century leap day", "value": "2000-02-29T00:00:00Z"},
    {"name": "end of year", "value": "2026-12-31T23:59:59.999999Z"},
    {"name": "year one", "value": "0001-01-01T00:00:00Z"}
  ],
  "invalid": [
    {"name": "offset instead of Z", "value": "2026-10-03T14:34:56+02:00", "field_errors": {"$": "invalid"}},
    {"name": "no zone", "value": "2026-10-03T12:34:56", "field_errors": {"$": "invalid"}},
    {"name": "lowercase z", "value": "2026-10-03T12:34:56z", "field_errors": {"$": "invalid"}},
    {"name": "space separator", "value": "2026-10-03 12:34:56Z", "field_errors": {"$": "invalid"}},
    {"name": "date only", "value": "2026-10-03", "field_errors": {"$": "invalid"}},
    {"name": "nanoseconds", "value": "2026-10-03T12:34:56.123456789Z", "field_errors": {"$": "invalid"}},
    {"name": "empty fraction", "value": "2026-10-03T12:34:56.Z", "field_errors": {"$": "invalid"}},
    {"name": "not a leap year", "value": "2026-02-29T00:00:00Z", "field_errors": {"$": "invalid"}},
    {"name": "century not a leap year", "value": "2100-02-29T00:00:00Z", "field_errors": {"$": "invalid"}},
    {"name": "month 13", "value": "2026-13-01T00:00:00Z", "field_errors": {"$": "invalid"}},
    {"name": "day zero", "value": "2026-10-00T00:00:00Z", "field_errors": {"$": "invalid"}},
    {"name": "april 31", "value": "2026-04-31T00:00:00Z", "field_errors": {"$": "invalid"}},
    {"name": "hour 24", "value": "2026-10-03T24:00:00Z", "field_errors": {"$": "invalid"}},
    {"name": "leap second", "value": "2026-12-31T23:59:60Z", "field_errors": {"$": "invalid"}},
    {"name": "year zero", "value": "0000-01-01T00:00:00Z", "field_errors": {"$": "invalid"}},
    {"name": "five digit year", "value": "12026-10-03T12:34:56Z", "field_errors": {"$": "invalid"}},
    {"name": "epoch number", "value": 1791000000, "field_errors": {"$": "invalid"}},
    {"name": "null", "value": null, "field_errors": {"$": "required"}},
    {"name": "object", "value": {"at": "2026-10-03T12:34:56Z"}, "field_errors": {"$": "invalid"}}
  ]
}
''',
  'lifecycle_event.json': r'''{
  "kind": "lifecycle_event",
  "contract_version": 1,
  "valid": [
    {"name": "hold applied", "value": {"event": "access_hold_applied", "member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "2026-10-03T12:00:00Z", "identity_revision": 7}},
    {"name": "hold released", "value": {"event": "access_hold_released", "member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "2026-10-03T12:00:00Z", "identity_revision": 8}},
    {"name": "scope revoked", "value": {"event": "scope_revoked", "member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "2026-10-03T12:00:00Z", "identity_revision": 9}},
    {"name": "account deactivated", "value": {"event": "account_deactivated", "member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "2026-10-03T12:00:00Z", "identity_revision": 10}},
    {"name": "deletion requested", "value": {"event": "deletion_requested", "member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "2026-10-03T12:00:00Z", "identity_revision": 11}},
    {"name": "cell transferred (identity_revision carries the member's Cells revision; v2 adds from_cell_id/to_cell_id before real owners hook it)", "value": {"event": "cell_transferred", "member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "2026-10-03T12:00:00Z", "identity_revision": 12}},
    {"name": "sessions revoked (device registrations bound to them end)", "value": {"event": "sessions_revoked", "member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "2026-10-03T12:00:00Z", "identity_revision": 13}},
    {"name": "membership deactivated (handover obligations recorded)", "value": {"event": "membership_deactivated", "member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "2026-10-03T12:00:00Z", "identity_revision": 14}},
    {"name": "membership restored after review", "value": {"event": "membership_restored", "member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "2026-10-03T12:00:00Z", "identity_revision": 15}}
  ],
  "invalid": [
    {"name": "unregistered event", "value": {"event": "member_promoted", "member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "2026-10-03T12:00:00Z", "identity_revision": 1}, "field_errors": {"event": "invalid"}},
    {"name": "missing event", "value": {"member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "2026-10-03T12:00:00Z", "identity_revision": 1}, "field_errors": {"event": "required"}},
    {"name": "bad instant and revision", "value": {"event": "scope_revoked", "member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "yesterday", "identity_revision": 0}, "field_errors": {"occurred_at": "invalid", "identity_revision": "invalid"}},
    {"name": "private context is not part of the event", "value": {"event": "scope_revoked", "member_id": "00000000-0000-4000-8000-000000000001", "occurred_at": "2026-10-03T12:00:00Z", "identity_revision": 1, "reason": "x"}, "field_errors": {"reason": "unknown_field"}}
  ]
}
''',
  'member_ref.json': r'''{
  "kind": "member_ref",
  "contract_version": 1,
  "valid": [
    {"name": "lowercase uuid", "value": {"member_id": "00000000-0000-4000-8000-000000000001"}}
  ],
  "invalid": [
    {"name": "missing member_id", "value": {}, "field_errors": {"member_id": "required"}},
    {"name": "null member_id", "value": {"member_id": null}, "field_errors": {"member_id": "required"}},
    {"name": "uppercase uuid is not canonical", "value": {"member_id": "00000000-0000-4000-8000-00000000000A"}, "field_errors": {"member_id": "invalid"}},
    {"name": "not a uuid", "value": {"member_id": "member-1"}, "field_errors": {"member_id": "invalid"}},
    {"name": "number", "value": {"member_id": 1}, "field_errors": {"member_id": "invalid"}},
    {"name": "phone number is never an identity", "value": {"member_id": "+447700900000"}, "field_errors": {"member_id": "invalid"}},
    {"name": "unknown key", "value": {"member_id": "00000000-0000-4000-8000-000000000001", "phone": "+447700900000"}, "field_errors": {"phone": "unknown_field"}},
    {"name": "not an object", "value": "00000000-0000-4000-8000-000000000001", "field_errors": {"$": "must_be_object"}},
    {"name": "null", "value": null, "field_errors": {"$": "must_be_object"}},
    {"name": "prototype-named key constructor", "value": {"member_id": "00000000-0000-4000-8000-000000000001", "constructor": "x"}, "field_errors": {"constructor": "unknown_field"}},
    {"name": "prototype-named key __proto__", "value": {"member_id": "00000000-0000-4000-8000-000000000001", "__proto__": "x"}, "field_errors": {"__proto__": "unknown_field"}},
    {"name": "prototype-named key toString", "value": {"member_id": "00000000-0000-4000-8000-000000000001", "toString": "x"}, "field_errors": {"toString": "unknown_field"}}
  ]
}
''',
  'money.json': r'''{
  "kind": "money",
  "contract_version": 1,
  "valid": [
    {"name": "two decimals (XTS is the ISO 4217 testing code, not church policy)", "value": {"amount": "12.50", "currency": "XTS"}},
    {"name": "integer amount", "value": {"amount": "100", "currency": "XTS"}},
    {"name": "zero", "value": {"amount": "0", "currency": "XTS"}},
    {"name": "zero with decimals", "value": {"amount": "0.00", "currency": "XTS"}},
    {"name": "beyond float precision", "value": {"amount": "999999999999999.999999", "currency": "XTS"}},
    {"name": "classic float trap", "value": {"amount": "0.30", "currency": "XTS"}}
  ],
  "invalid": [
    {"name": "JSON number (float) amount", "value": {"amount": 12.5, "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "JSON integer amount", "value": {"amount": 12, "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "comma decimal", "value": {"amount": "12,50", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "thousands separator", "value": {"amount": "1,000.00", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "leading zero", "value": {"amount": "012.50", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "leading plus", "value": {"amount": "+12.50", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "negative zero", "value": {"amount": "-0.00", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "trailing point", "value": {"amount": "12.", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "leading point", "value": {"amount": ".5", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "exponent", "value": {"amount": "1e3", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "too many integer digits", "value": {"amount": "1000000000000000", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "too many fraction digits", "value": {"amount": "1.0000001", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "whitespace", "value": {"amount": " 12.50", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "currency symbol", "value": {"amount": "12.50", "currency": "K"}, "field_errors": {"currency": "invalid"}},
    {"name": "lowercase currency", "value": {"amount": "12.50", "currency": "xts"}, "field_errors": {"currency": "invalid"}},
    {"name": "missing currency", "value": {"amount": "12.50"}, "field_errors": {"currency": "required"}},
    {"name": "missing amount", "value": {"currency": "XTS"}, "field_errors": {"amount": "required"}},
    {"name": "unknown key", "value": {"amount": "12.50", "currency": "XTS", "scale": 2}, "field_errors": {"scale": "unknown_field"}},
    {"name": "not an object", "value": "12.50 XTS", "field_errors": {"$": "must_be_object"}},
    {"name": "negative amount (signs belong to owner rules)", "value": {"amount": "-3.25", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "negative integer", "value": {"amount": "-1", "currency": "XTS"}, "field_errors": {"amount": "invalid"}},
    {"name": "prototype-named key constructor", "value": {"amount": "1.00", "currency": "XTS", "constructor": "x"}, "field_errors": {"constructor": "unknown_field"}},
    {"name": "prototype-named key __proto__", "value": {"amount": "1.00", "currency": "XTS", "__proto__": "x"}, "field_errors": {"__proto__": "unknown_field"}},
    {"name": "prototype-named key toString", "value": {"amount": "1.00", "currency": "XTS", "toString": "x"}, "field_errors": {"toString": "unknown_field"}}
  ]
}
''',
  'notification_key.json': r'''{
  "kind": "notification_key",
  "contract_version": 1,
  "valid": [
    {"name": "full logical key", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 3, "recipient_member_id": "00000000-0000-4000-8000-000000000002", "reminder_kind": "fixture_nudge", "scheduled_at": "2026-10-04T07:00:00.000000Z"}}
  ],
  "invalid": [
    {"name": "everything missing", "value": {}, "field_errors": {"source_type": "required", "source_id": "required", "source_revision": "required", "recipient_member_id": "required", "reminder_kind": "required", "scheduled_at": "required"}},
    {"name": "local time without zone", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 3, "recipient_member_id": "00000000-0000-4000-8000-000000000002", "reminder_kind": "fixture_nudge", "scheduled_at": "2026-10-04T07:00:00"}, "field_errors": {"scheduled_at": "invalid"}},
    {"name": "account is not a recipient member", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 3, "recipient_auth_user_id": "00000000-0000-4000-8000-000000000002", "reminder_kind": "fixture_nudge", "scheduled_at": "2026-10-04T07:00:00Z"}, "field_errors": {"recipient_member_id": "required", "recipient_auth_user_id": "unknown_field"}}
  ]
}
''',
  'source_ref.json': r'''{
  "kind": "source_ref",
  "contract_version": 1,
  "valid": [
    {"name": "first revision", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1}},
    {"name": "largest JS-safe revision", "value": {"source_type": "a", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 9007199254740991}},
    {"name": "longest token (63 chars)", "value": {"source_type": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1}},
    {"name": "integral value written with an exponent (1e3)", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1e3}},
    {"name": "integral value written with a fraction (1.0)", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1.0}},
    {"name": "integral value written as 2E1", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 2E1}}
  ],
  "invalid": [
    {"name": "everything missing", "value": {}, "field_errors": {"source_type": "required", "source_id": "required", "source_revision": "required"}},
    {"name": "revision zero", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 0}, "field_errors": {"source_revision": "invalid"}},
    {"name": "negative revision", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": -1}, "field_errors": {"source_revision": "invalid"}},
    {"name": "fractional revision", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1.5}, "field_errors": {"source_revision": "invalid"}},
    {"name": "revision as string", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": "1"}, "field_errors": {"source_revision": "invalid"}},
    {"name": "revision beyond JS-safe range", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 9007199254740992}, "field_errors": {"source_revision": "invalid"}},
    {"name": "source_type with capitals", "value": {"source_type": "FixtureCounter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1}, "field_errors": {"source_type": "invalid"}},
    {"name": "source_type with dot", "value": {"source_type": "fixture.counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1}, "field_errors": {"source_type": "invalid"}},
    {"name": "source_type starting with digit", "value": {"source_type": "1counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1}, "field_errors": {"source_type": "invalid"}},
    {"name": "source_type longer than 63", "value": {"source_type": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1}, "field_errors": {"source_type": "invalid"}},
    {"name": "empty source_type", "value": {"source_type": "", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1}, "field_errors": {"source_type": "invalid"}},
    {"name": "null source_id", "value": {"source_type": "fixture_counter", "source_id": null, "source_revision": 1}, "field_errors": {"source_id": "required"}},
    {"name": "unknown key", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1, "title": "x"}, "field_errors": {"title": "unknown_field"}},
    {"name": "non-integral exponent (1e-1)", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1e-1}, "field_errors": {"source_revision": "invalid"}},
    {"name": "very large exponent (1e300)", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1e300}, "field_errors": {"source_revision": "invalid"}},
    {"name": "beyond JS-safe written as exponent (1e16)", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1e16}, "field_errors": {"source_revision": "invalid"}},
    {"name": "prototype-named key constructor", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1, "constructor": "x"}, "field_errors": {"constructor": "unknown_field"}},
    {"name": "prototype-named key __proto__", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1, "__proto__": "x"}, "field_errors": {"__proto__": "unknown_field"}},
    {"name": "prototype-named key toString", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "source_revision": 1, "toString": "x"}, "field_errors": {"toString": "unknown_field"}}
  ]
}
''',
  'task_source.json': r'''{
  "kind": "task_source",
  "contract_version": 1,
  "valid": [
    {"name": "source and purpose", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "purpose": "fixture_review"}}
  ],
  "invalid": [
    {"name": "missing purpose", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001"}, "field_errors": {"purpose": "required"}},
    {"name": "purpose with spaces", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "purpose": "fixture review"}, "field_errors": {"purpose": "invalid"}},
    {"name": "revision does not belong to a task identity", "value": {"source_type": "fixture_counter", "source_id": "00000000-0000-4000-8000-000000000001", "purpose": "fixture_review", "source_revision": 1}, "field_errors": {"source_revision": "unknown_field"}},
    {"name": "not an object", "value": 3, "field_errors": {"$": "must_be_object"}}
  ]
}
''',
  'zoned_local.json': r'''{
  "kind": "zoned_local",
  "contract_version": 1,
  "valid": [
    {"name": "UTC (TEST FIXTURE zone, not church policy)", "value": {"local": "2026-10-04T09:00:00", "zone": "UTC"}},
    {"name": "area/location zone, wall time in a DST gap stays intent", "value": {"local": "2026-03-29T01:30:00", "zone": "Europe/London"}},
    {"name": "area/region/location zone", "value": {"local": "2026-10-04T09:00:00", "zone": "America/Argentina/Buenos_Aires"}},
    {"name": "another area", "value": {"local": "2026-10-04T09:00:00", "zone": "Asia/Tokyo"}},
    {"name": "64-char zone (shape only; existence is a server check)", "value": {"local": "2026-10-04T09:00:00", "zone": "Pacific/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}}
  ],
  "invalid": [
    {"name": "local with Z is an instant, not local intent", "value": {"local": "2026-10-04T09:00:00Z", "zone": "UTC"}, "field_errors": {"local": "invalid"}},
    {"name": "local with offset", "value": {"local": "2026-10-04T09:00:00+02:00", "zone": "UTC"}, "field_errors": {"local": "invalid"}},
    {"name": "local with fraction", "value": {"local": "2026-10-04T09:00:00.5", "zone": "UTC"}, "field_errors": {"local": "invalid"}},
    {"name": "local without seconds", "value": {"local": "2026-10-04T09:00", "zone": "UTC"}, "field_errors": {"local": "invalid"}},
    {"name": "impossible date", "value": {"local": "2026-02-30T09:00:00", "zone": "UTC"}, "field_errors": {"local": "invalid"}},
    {"name": "missing zone (never inferred)", "value": {"local": "2026-10-04T09:00:00"}, "field_errors": {"zone": "required"}},
    {"name": "offset is not a zone", "value": {"local": "2026-10-04T09:00:00", "zone": "+02:00"}, "field_errors": {"zone": "invalid"}},
    {"name": "path traversal", "value": {"local": "2026-10-04T09:00:00", "zone": "../etc/passwd"}, "field_errors": {"zone": "invalid"}},
    {"name": "empty zone", "value": {"local": "2026-10-04T09:00:00", "zone": ""}, "field_errors": {"zone": "invalid"}},
    {"name": "trailing slash", "value": {"local": "2026-10-04T09:00:00", "zone": "Africa/"}, "field_errors": {"zone": "invalid"}},
    {"name": "zone not a string", "value": {"local": "2026-10-04T09:00:00", "zone": 2}, "field_errors": {"zone": "invalid"}},
    {"name": "65-char zone", "value": {"local": "2026-10-04T09:00:00", "zone": "Pacific/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "field_errors": {"zone": "invalid"}},
    {"name": "Etc alias", "value": {"local": "2026-10-04T09:00:00", "zone": "Etc/UTC"}, "field_errors": {"zone": "invalid"}},
    {"name": "signed Etc zone", "value": {"local": "2026-10-04T09:00:00", "zone": "Etc/GMT-2"}, "field_errors": {"zone": "invalid"}},
    {"name": "legacy POSIX-style zone", "value": {"local": "2026-10-04T09:00:00", "zone": "EST5EDT"}, "field_errors": {"zone": "invalid"}},
    {"name": "Factory", "value": {"local": "2026-10-04T09:00:00", "zone": "Factory"}, "field_errors": {"zone": "invalid"}},
    {"name": "posix/ tree", "value": {"local": "2026-10-04T09:00:00", "zone": "posix/Europe/London"}, "field_errors": {"zone": "invalid"}},
    {"name": "right/ tree", "value": {"local": "2026-10-04T09:00:00", "zone": "right/UTC"}, "field_errors": {"zone": "invalid"}},
    {"name": "legacy country alias", "value": {"local": "2026-10-04T09:00:00", "zone": "US/Eastern"}, "field_errors": {"zone": "invalid"}},
    {"name": "UCT alias", "value": {"local": "2026-10-04T09:00:00", "zone": "UCT"}, "field_errors": {"zone": "invalid"}},
    {"name": "GMT alias", "value": {"local": "2026-10-04T09:00:00", "zone": "GMT"}, "field_errors": {"zone": "invalid"}},
    {"name": "too many segments", "value": {"local": "2026-10-04T09:00:00", "zone": "Europe/London/Extra/More"}, "field_errors": {"zone": "invalid"}},
    {"name": "lowercase area", "value": {"local": "2026-10-04T09:00:00", "zone": "europe/London"}, "field_errors": {"zone": "invalid"}},
    {"name": "not an object", "value": "2026-10-04T09:00:00", "field_errors": {"$": "must_be_object"}},
    {"name": "prototype-named key constructor", "value": {"local": "2026-10-04T09:00:00", "zone": "UTC", "constructor": "x"}, "field_errors": {"constructor": "unknown_field"}},
    {"name": "prototype-named key __proto__", "value": {"local": "2026-10-04T09:00:00", "zone": "UTC", "__proto__": "x"}, "field_errors": {"__proto__": "unknown_field"}},
    {"name": "prototype-named key toString", "value": {"local": "2026-10-04T09:00:00", "zone": "UTC", "toString": "x"}, "field_errors": {"toString": "unknown_field"}}
  ]
}
''',
};
